#!/bin/bash

#python3 activity_graph_classification.py --ds_name=MHEALTH --ds_variant=gaussian_win --model_name=GAT --epochs=500 --batch_size=64 --init_lr=0.001 --lr_reduce_factor=0.5 --lr_reduce_factor_ft=0.1 --lr_schedule_patience=10 --min_lr=1e-6 --num_layers=3 --input_dim=128 --hidden_dim=64 --out_dim=12 --aggr=mean --global_pooling=max --conv_dropout=0.2 --classifier_dropout=0.5 --batch_norm
#python3 activity_graph_classification.py --ds_name=MHEALTH --ds_variant=gaussian_win --model_name=GAT2 --epochs=500 --batch_size=64 --init_lr=0.001 --lr_reduce_factor=0.5 --lr_reduce_factor_ft=0.1 --lr_schedule_patience=10 --min_lr=1e-6 --num_layers=3 --input_dim=128 --hidden_dim=64 --out_dim=12 --aggr=mean --global_pooling=max --conv_dropout=0.5 --classifier_dropout=0.5 --batch_norm
#python3 activity_graph_classification.py --ds_name=MHEALTH --ds_variant=gaussian_win --model_name=transf --epochs=500 --batch_size=64 --init_lr=0.001 --lr_reduce_factor=0.5 --lr_reduce_factor_ft=0.1 --lr_schedule_patience=10 --min_lr=1e-6 --num_layers=3 --input_dim=128 --hidden_dim=64 --out_dim=12 --aggr=mean --global_pooling=max --conv_dropout=0.5 --classifier_dropout=0.5 --batch_norm
#python3 activity_graph_classification.py --ds_name=MHEALTH --ds_variant=gaussian_win --model_name=graphconv --epochs=500 --batch_size=64 --init_lr=0.001 --lr_reduce_factor=0.5 --lr_reduce_factor_ft=0.1 --lr_schedule_patience=10 --min_lr=1e-6 --num_layers=3 --input_dim=128 --hidden_dim=64 --out_dim=12 --aggr=mean --global_pooling=max --conv_dropout=0.5 --classifier_dropout=0.5 --batch_norm
#
#python3 activity_graph_classification.py --ds_name=MHEALTH --ds_variant=corrcoef_all --model_name=graphconv --epochs=500 --batch_size=64 --init_lr=0.001 --lr_reduce_factor=0.5 --lr_reduce_factor_ft=0.1 --lr_schedule_patience=20 --min_lr=1e-6 --num_layers=3 --input_dim=128 --hidden_dim=64 --out_dim=12 --aggr=mean --global_pooling=max --conv_dropout=0.2 --classifier_dropout=0.5 --batch_norm --patience_tr=50
#python3 activity_graph_classification.py --ds_name=MHEALTH --ds_variant=corrcoef_win --model_name=graphconv --epochs=500 --batch_size=64 --init_lr=0.001 --lr_reduce_factor=0.5 --lr_reduce_factor_ft=0.1 --lr_schedule_patience=20 --min_lr=1e-6 --num_layers=3 --input_dim=128 --hidden_dim=64 --out_dim=12 --aggr=mean --global_pooling=max --conv_dropout=0.2 --classifier_dropout=0.5 --batch_norm --patience_tr=50

python3 activity_graph_classification.py --ds_name=UCIHAR --ds_variant=corrcoef_all --model_name=gat2 --heads=4 --epochs=500 --batch_size=64 --init_lr=1.54e-3 --w_decay=5.07e-4 --lr_reduce_factor=0.5 --lr_reduce_factor_ft=0.1 --lr_schedule_patience=30 --min_lr=1e-6 --num_layers=3 --input_dim=128 --hidden_dim=64 --out_dim=6 --aggr=max --global_pooling=add --conv_dropout=0.3 --classifier_dropout=0.1 --batch_norm
#python3 activity_graph_classification.py --ds_name=MHEALTH --ds_variant=corrcoef_win --model_name=gat2 --epochs=500 --batch_size=64 --init_lr=0.001 --lr_reduce_factor=0.5 --lr_reduce_factor_ft=0.1 --lr_schedule_patience=20 --min_lr=1e-6 --num_layers=3 --input_dim=128 --hidden_dim=64 --out_dim=12 --aggr=mean --global_pooling=max --conv_dropout=0.2 --classifier_dropout=0.5 --batch_norm --patience_tr=50



#python3 training_ensemble.py --ds_name=MHEALTH --ds_variant=ensemble --activity=0 --model_name=graphconv --epochs=500 --batch_size=64 --init_lr=0.001 --lr_reduce_factor=0.5 --lr_reduce_factor_ft=0.1 --lr_schedule_patience=20 --min_lr=1e-6 --num_layers=3 --input_dim=128 --hidden_dim=64 --out_dim=1 --aggr=mean --global_pooling=max --conv_dropout=0.2 --classifier_dropout=0.5 --batch_norm --patience_tr=50 --scheduler
